import type { PersonaConfig } from "./types";

// Display-only persona configs for the client (subset of server configs)
export const PERSONAS: PersonaConfig[] = [
  {
    id: "sarah",
    name: "Sarah Chen",
    title: "Head of People & Culture",
    company: "TechVenture Inc.",
    personality: "Warm, encouraging, and genuinely curious about people.",
    industry: "Tech Startup",
    difficulty: "easy",
    voiceName: "Leda",
    interviewStyle:
      "Opens with friendly small talk. Focuses on behavioral questions using STAR method.",
    quirks: [],
    avatar: {
      emoji: "\u{1F60A}",
      color: "emerald",
      gradient: "from-emerald-500 to-teal-600",
    },
  },
  {
    id: "david",
    name: "David Morrison",
    title: "Vice President, Strategic Operations",
    company: "Morrison & Partners Global",
    personality: "Direct, efficient, and results-oriented.",
    industry: "Fortune 500 / Management Consulting",
    difficulty: "hard",
    voiceName: "Charon",
    interviewStyle:
      "Minimal small talk. Probing questions. Challenges answers. Tests composure.",
    quirks: [],
    avatar: {
      emoji: "\u{1F610}",
      color: "rose",
      gradient: "from-rose-500 to-red-600",
    },
  },
  {
    id: "maya",
    name: "Maya Patel",
    title: "Senior Engineering Manager",
    company: "CloudScale Technologies",
    personality: "Analytical, fair, and deeply technical.",
    industry: "Big Tech / Cloud Infrastructure",
    difficulty: "medium",
    voiceName: "Kore",
    interviewStyle:
      "Mix of behavioral and technical questions. Probes for depth. Evaluates thinking process.",
    quirks: [],
    avatar: {
      emoji: "\u{1F9D0}",
      color: "blue",
      gradient: "from-blue-500 to-indigo-600",
    },
  },
];

export const RANDOM_PERSONA = {
  id: "random",
  name: "Random",
  title: "AI-Generated Interviewer",
  company: "Mystery Corp",
  personality: "A unique persona generated by AI for each session.",
  industry: "Varies",
  difficulty: "medium" as const,
  voiceName: "",
  interviewStyle: "Surprise! Every session is different.",
  quirks: [],
  avatar: {
    emoji: "\u{1F3B2}",
    color: "purple",
    gradient: "from-purple-500 to-violet-600",
  },
};
